export const ADD_POLL = 'ADD_POLL';
export const EDIT_POLL = 'EDIT_POLL';
export const DELETE_POLL = 'DELETE_POLL';
export const VOTE_ON_POLL = 'VOTE_ON_POLL';
export const CHANGE_SELECTED_OPTION = 'CHANGE_SELECTED_OPTION';

export const ADD_OWN_POLL = 'ADD_OWN_POLL';
export const DELETE_OWN_POLL = 'DELETE_OWN_POLL';

export const ADD_USER = 'ADD_USER';
export const CHANGE_USER_PASSWORD = 'CHANGE_USER_PASSWORD';

export const ADD_AUTHED_USER = 'ADD_AUTHED_USER';
export const REMOVE_AUTHED_USER = 'REMOVE_AUTHED_USER';

export const CHANGE_SIGNUP_PASSWORD = 'CHANGE_SIGNUP_PASSWORD';
export const CHANGE_SIGNUP_USERNAME = 'CHANGE_SIGNUP_USERNAME';
export const CHANGE_SIGNUP_NAME = 'CHANGE_SIGNUP_NAME';
export const CLEAR_SIGNUP_FORM = 'CLEAR_SIGNUP_FORM';

export const CHANGE_LOGIN_PASSWORD = 'CHANGE_LOGIN_PASSWORD';
export const CHANGE_LOGIN_USERNAME = 'CHANGE_LOGIN_USERNAME';
export const CLEAR_LOGIN_FORM = 'CLEAR_LOGIN_FORM';

export const INSERT_POLL_FORM_OPTIONS = 'INSERT_POLL_FORM_OPTIONS';
export const CHANGE_POLL_FORM_TYPE = 'CHANGE_POLL_FORM_TYPE';
export const CHANGE_POLL_FORM_NAME = 'CHANGE_POLL_FORM_NAME';
export const CHANGE_POLL_FORM_OPTIONS = 'CHANGE_POLL_FORM_OPTIONS';
export const CHANGE_POLL_FORM_OPTION = 'CHANGE_POLL_FORM_OPTION'
export const ADD_POLL_FORM_OPTIONS_INPUT = 'ADD_POLL_FORM_OPTIONS_INPUT';
export const REMOVE_POLL_FORM_OPTIONS_INPUT = 'REMOVE_POLL_FORM_OPTIONS_INPUT';
export const CLEAR_POLL_FORM = 'CLEAR_POLL_FORM';

export const SET_IS_FETCHING = 'SET_IS_FETCHING';

export const CHANGE_POLLS_PAGE = 'CHANGE_POLLS_PAGE';
export const NEXT_POLLS_PAGE = 'NEXT_POLLS_PAGE';
export const PREVIOUS_POLLS_PAGE = 'PREVIOUS_POLLS_PAGE';

export const CHANGE_USERS_PAGE = 'CHANGE_USERS_PAGE';
export const NEXT_USERS_PAGE = 'NEXT_USERS_PAGE';
export const PREVIOUS_USERS_PAGE = 'PREVIOUS_USERS_PAGE';
